NDefines.NGame.START_DATE = "2020.4.2.12"
NDefines.NGame.END_DATE = "2028.4.2.12"
NDefines.NDiplomacy.BASE_PEACE_LIBERATE_FACTOR = 0
NDefines.NDiplomacy.TENSION_FACTION_JOIN = 0
NDefines.NAI.DIPLOMACY_FACTION_GLOBAL_TENSION_FACTOR = 0
NDefines.NAI.DIPLOMACY_FACTION_WAR_RELUCTANCE = -75

NAir = {
	AIR_WING_MAX_STATS_ATTACK = 100,
	AIR_WING_MAX_STATS_DEFENCE = 100,
	AIR_WING_MAX_STATS_AGILITY = 100,
	AIR_WING_MAX_STATS_SPEED = 3000,
	AIR_WING_MAX_STATS_BOMBING = 100,
	AIR_WING_MAX_SIZE = 1000,
	AIR_WING_AVERAGE_SIZE = 48,
}