NDefines.NGame.START_DATE = "2020.4.2.12"
NDefines.NGame.END_DATE = "2028.4.2.12"
NDefines.NDiplomacy.BASE_PEACE_LIBERATE_FACTOR = 0
NDefines.NDiplomacy.TAKE_STATES_LIBERATE_COST_MULT = 50
NDefines.NDiplomacy.TENSION_FACTION_JOIN = 0
NDefines.NAI.DIPLOMACY_FACTION_GLOBAL_TENSION_FACTOR = 0
NDefines.NAI.DIPLOMACY_FACTION_WAR_RELUCTANCE = -75